apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ['sh', '-c', 'sleep 5; echo post-sync']
      restartPolicy: Never
  backoffLimit: 0
