apiVersion: batch/v1
kind: Job
metadata:
  name: sync-2
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ['sh', '-c', 'sleep 5; echo sync-2']
      restartPolicy: Never
  backoffLimit: 0
