apiVersion: batch/v1
kind: Job
metadata:
  name: sync-1
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ['sh', '-c', 'sleep 5; echo sync-1']
      restartPolicy: Never
  backoffLimit: 0
